version: '3'
services:
  db:
    image: library/postgres:13.0
    container_name: postgresql
    ports:
    - 5432:5432
    volumes:
    - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: mercari_db
      POSTGRES_USER: mercari
      POSTGRES_PASSWORD: mercari
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db