version: '3'
services:
  db:
    image: library/postgres:13.0
    container_name: postgresql
    ports:
    - 5432:5432
    volumes:
    - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: mercari_db
      POSTGRES_USER: mercari
      POSTGRES_PASSWORD: mercari
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always

  django:
    build: /django/
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  nginx:
    container_name: nginx
    image: nginx:stable
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
    restart: always
    ports:
      - "80:80"
      - "443:443"
    logging:
      options:
        max-size: 5m
        max-file: "10"
    networks:
      - common_link